title: default

form:
  fields:
    tabs:
      type: tabs
      active: 1
      fields:
        inhalt:
          type: tab
          title: THEME_TRAVELER.ADMIN.TAB.CONTENT
          fields:
            header.title:
              type: text
              autofocus: true
              label: THEME_TRAVELER.ADMIN.FIELDS.TITLE.LABEL
            header.image:
              type: mediapicker
              label: THEME_TRAVELER.ADMIN.FIELDS.PREVIEW_IMAGE.LABEL
              preview_images: true
            content:
              type: section
              title: THEME_TRAVELER.ADMIN.SECTION.CONTENT
              underline: true
              fields:
                content:
                  type: markdown
                  validate:
                    type: textarea
            media:
              type: section
              title: THEME_TRAVELER.ADMIN.SECTION.MEDIA
              underline: true
              fields:
                header.media_order:
                  type: pagemedia
                  label: PLUGIN_ADMIN.PAGE_MEDIA
