title: default

form:
  fields:
    tabs:
      type: tabs
      active: 1
      fields:
        inhalt:
          type: tab
          title: THEME_TRAVELER.ADMIN.TAB.CONTENT
          fields:
            header.title:
              type: text
              autofocus: true
              label: THEME_TRAVELER.ADMIN.FIELDS.TITLE.LABEL
            header.image:
              type: file
              label: THEME_TRAVELER.ADMIN.FIELDS.IMAGE_HEADER.LABEL
              destination: '@self/header'
              accept:
                - image/*
            content:
              type: markdown
              validate:
                type: textarea
            header.media_order:
              type: pagemedia
              label: PLUGIN_ADMIN.PAGE_MEDIA
